//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigMenu
    {
        public int ConfId { get; set; }
        public Nullable<int> ConfTipTrabaja { get; set; }
        public Nullable<int> ConfButton { get; set; }
        public Nullable<int> ConfEstado { get; set; }
    
        public virtual ConfigButton ConfigButton { get; set; }
        public virtual TipoTrabajador TipoTrabajador { get; set; }
    }
}
