//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigButton
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfigButton()
        {
            this.ConfigMenu = new HashSet<ConfigMenu>();
        }
    
        public int ConfButId { get; set; }
        public string ConfButName { get; set; }
        public Nullable<int> ConfButEstado { get; set; }
        public Nullable<int> ConfPadre { get; set; }
        public string ConfFuncion { get; set; }
        public string ConfControlador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigMenu> ConfigMenu { get; set; }
    }
}
