//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.HistClinico = new HashSet<HistClinico>();
        }
    
        public int ConsCodigo { get; set; }
        public Nullable<int> CodPaciente { get; set; }
        public Nullable<int> CodTrabajador { get; set; }
        public Nullable<int> ConsEstado { get; set; }
        public Nullable<System.DateTime> ConsFecha { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Trabajador Trabajador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistClinico> HistClinico { get; set; }
    }
}
