//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especialidad()
        {
            this.Medico = new HashSet<Medico>();
        }
    
        public string CodEspe { get; set; }

        [Required(ErrorMessage = "dato obligatorio")]
        [RegularExpression("[A-Za-z ñÑ]+", ErrorMessage = "Solo Letras o Espacios")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "minimo 3 caracteres")]

        public string NombEspe { get; set; }


        [Required(ErrorMessage = "dato obligatorio")]
        [RegularExpression("[A-Za-zñÑ]+", ErrorMessage = "Solo Letras")]
        [StringLength(12, MinimumLength = 6, ErrorMessage = "minimo 6 caracteres")]
        public string EstaEspe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medico> Medico { get; set; }
    }
}
