//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistClinico
    {
        public int HistCodigo { get; set; }
        public Nullable<int> CodConsulta { get; set; }
        public Nullable<int> HistEstado { get; set; }
        public string Histsintomas { get; set; }
        public string HistTratamiento { get; set; }
        public string HistExamenes { get; set; }
        public string HistObservaciones { get; set; }
    
        public virtual Consulta Consulta { get; set; }
    }
}
