//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIOATENCION
    {
        public string ID_HORARIOTENCION { get; set; }
        public string CODMED { get; set; }
        public string ID_HORA { get; set; }
        public Nullable<System.DateTime> FECHACITA { get; set; }
        public string ESTADO { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual HORAS HORAS { get; set; }
    }
}
