//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.HORARIOATENCION = new HashSet<HORARIOATENCION>();
            this.RESERVACION = new HashSet<RESERVACION>();
        }
    
        public string Codmed { get; set; }
        public string CodEspe { get; set; }
        public string NomTra { get; set; }
        public string ApeTra { get; set; }
        public string Genero { get; set; }
        public string DniTra { get; set; }
        public string CorreoTra { get; set; }
        public string EstaTra { get; set; }
        public string Codmod { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIOATENCION> HORARIOATENCION { get; set; }
        public virtual MODULO MODULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVACION> RESERVACION { get; set; }
    }
}
