//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.RESERVACION = new HashSet<RESERVACION>();
        }
    
        public string Codmed { get; set; }
        public string CodEspe { get; set; }
        public string NomTra { get; set; }
        public string ApeTra { get; set; }
        public string Genero { get; set; }
        public string DniTra { get; set; }
        public string CorreoTra { get; set; }
        public string EstaTra { get; set; }
        public string Codmod { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual MODULO MODULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVACION> RESERVACION { get; set; }
    }
}
