//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bdclinicEntities : DbContext
    {
        public bdclinicEntities()
            : base("name=bdclinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<PAYMET> PAYMET { get; set; }
        public virtual DbSet<RESERVACION> RESERVACION { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    
        public virtual int SP_ADIMEDICO(string cODESPE, string nOMTRA, string aPETRA, string gENERO, string dNITRA, string cORREOTRA, string eSTATRA, string cODMOD)
        {
            var cODESPEParameter = cODESPE != null ?
                new ObjectParameter("CODESPE", cODESPE) :
                new ObjectParameter("CODESPE", typeof(string));
    
            var nOMTRAParameter = nOMTRA != null ?
                new ObjectParameter("NOMTRA", nOMTRA) :
                new ObjectParameter("NOMTRA", typeof(string));
    
            var aPETRAParameter = aPETRA != null ?
                new ObjectParameter("APETRA", aPETRA) :
                new ObjectParameter("APETRA", typeof(string));
    
            var gENEROParameter = gENERO != null ?
                new ObjectParameter("GENERO", gENERO) :
                new ObjectParameter("GENERO", typeof(string));
    
            var dNITRAParameter = dNITRA != null ?
                new ObjectParameter("DNITRA", dNITRA) :
                new ObjectParameter("DNITRA", typeof(string));
    
            var cORREOTRAParameter = cORREOTRA != null ?
                new ObjectParameter("CORREOTRA", cORREOTRA) :
                new ObjectParameter("CORREOTRA", typeof(string));
    
            var eSTATRAParameter = eSTATRA != null ?
                new ObjectParameter("ESTATRA", eSTATRA) :
                new ObjectParameter("ESTATRA", typeof(string));
    
            var cODMODParameter = cODMOD != null ?
                new ObjectParameter("CODMOD", cODMOD) :
                new ObjectParameter("CODMOD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADIMEDICO", cODESPEParameter, nOMTRAParameter, aPETRAParameter, gENEROParameter, dNITRAParameter, cORREOTRAParameter, eSTATRAParameter, cODMODParameter);
        }
    
        public virtual int SP_ADIPACIENTES(string nOMPAC, string aPEPAC, string tELEPAC, string dNIPAC, string gENERO, string eSTAPAC)
        {
            var nOMPACParameter = nOMPAC != null ?
                new ObjectParameter("NOMPAC", nOMPAC) :
                new ObjectParameter("NOMPAC", typeof(string));
    
            var aPEPACParameter = aPEPAC != null ?
                new ObjectParameter("APEPAC", aPEPAC) :
                new ObjectParameter("APEPAC", typeof(string));
    
            var tELEPACParameter = tELEPAC != null ?
                new ObjectParameter("TELEPAC", tELEPAC) :
                new ObjectParameter("TELEPAC", typeof(string));
    
            var dNIPACParameter = dNIPAC != null ?
                new ObjectParameter("DNIPAC", dNIPAC) :
                new ObjectParameter("DNIPAC", typeof(string));
    
            var gENEROParameter = gENERO != null ?
                new ObjectParameter("GENERO", gENERO) :
                new ObjectParameter("GENERO", typeof(string));
    
            var eSTAPACParameter = eSTAPAC != null ?
                new ObjectParameter("ESTAPAC", eSTAPAC) :
                new ObjectParameter("ESTAPAC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ADIPACIENTES", nOMPACParameter, aPEPACParameter, tELEPACParameter, dNIPACParameter, gENEROParameter, eSTAPACParameter);
        }
    
        public virtual int spadiEsp(string nom, string estado)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spadiEsp", nomParameter, estadoParameter);
        }
    }
}
