//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaP2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajador()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int TraCodigo { get; set; }
        public Nullable<int> PerCodigo { get; set; }
        public Nullable<int> EspCodigo { get; set; }
        public Nullable<int> TipCodigo { get; set; }
        public Nullable<int> TraHorasTrabajo { get; set; }
        public Nullable<int> TraEstado { get; set; }
        public string TraUsuario { get; set; }
        public string TraContrasena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TipoTrabajador TipoTrabajador { get; set; }
    }
}
